name: FollowSocial
favicon: null
layout_spectrum: 0.33023927197791636
typography_spectrum: 0.49519609403796494
title: FollowSocial
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0f12'
    - '#f1ffff'
    - '#c0b5b3'
    - '#8b7664'
    - '#890016'
  brandStrength: 0
  lightness: 0.3600951600819826
  saturation: 0.1767148356884718
  rhythmicContrast: 0.1594524432439357
purpose: []
