name: FollowSocial
favicon: null
layout_spectrum: 0
typography_spectrum: 0.49465
title: FollowSocial
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e2ccc0'
    - '#b58a46'
    - '#211c0d'
    - '#c30000'
    - '#356a1a'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
