name: FollowSocial
favicon: null
layout_spectrum: 0
typography_spectrum: 0.49465
title: FollowSocial
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060000'
    - '#ad5f21'
    - '#fcfae5'
    - '#db9823'
    - '#6b1703'
  brandStrength: 0.5
  lightness: 0.3600951600819826
  saturation: 0.1767148356884718
  rhythmicContrast: 0.75
purpose: []
